"""pagentv4 —— 顶层门面。

模块分层：
- core/       Agent + Message + Provider + Tool + Event
- runtime/    Runner + Conversation（编排 + 持久化）
- sandbox/    伴身电脑（Backend Protocol + Sandbox 门面 + tools 适配）
- adapters/   与外部协议的编解码（当前只有 ACP）

用户面：`from pagentv4 import Agent, Runner, ...` 全部保留，
子包深路径也稳定可用（`from pagentv4.core import ...`）。
"""

from .adapters import decode_event_line, encode_event_line
from .core import (
    Agent,
    AssistantChunk,
    AudioUrl,
    DeepSeek,
    Event,
    FunctionTool,
    ImageUrl,
    Kimi,
    LongCat,
    Message,
    Messages,
    MiMo,
    Ollama,
    Provider,
    ReasoningDelta,
    RunBegin,
    Sglang,
    StopReason,
    TextChunk,
    TextDelta,
    ThinkingChunk,
    ToolCall,
    ToolCallBegin,
    ToolOutput,
    ToolResult,
    TurnBegin,
    TurnEnd,
    TurnResult,
    UserChunk,
    Vllm,
    reply_text,
    to_openai_tools,
    tool,
)
from .runtime import (
    ArunReturnType,
    ConversationStore,
    EventHandler,
    JsonlConversationStore,
    Runner,
    SqliteConversationStore,
    Thread,
    ThreadSpec,
    default_conversations_root,
    default_threads_root,
    validate_thread_id,
)
from .sandbox import (
    Backend,
    BackendGuard,
    BackendIdentity,
    CommandResult,
    DirEntry,
    LocalBackend,
    Sandbox,
    SandboxDeadError,
    SandboxLimits,
    SandboxSpec,
    SshConnection,
    build_backend,
    build_computer_description,
    build_sandbox_tools,
)
from .skills import (
    Skill,
    SkillDiscoveryError,
    SkillRegistry,
    build_skills_system_prompt,
    default_skill_roots,
    load_skill,
    load_skills_from_root,
    make_use_skill_tool,
)

__all__ = [
    "Agent",
    "ArunReturnType",
    "AssistantChunk",
    "AudioUrl",
    "Backend",
    "BackendGuard",
    "BackendIdentity",
    "CommandResult",
    "ConversationStore",
    "DeepSeek",
    "DirEntry",
    "Event",
    "EventHandler",
    "FunctionTool",
    "ImageUrl",
    "JsonlConversationStore",
    "Kimi",
    "LocalBackend",
    "LongCat",
    "Message",
    "Messages",
    "MiMo",
    "Ollama",
    "Provider",
    "ReasoningDelta",
    "RunBegin",
    "Runner",
    "Sandbox",
    "SandboxDeadError",
    "SandboxLimits",
    "SandboxSpec",
    "Sglang",
    "SshConnection",
    "Skill",
    "SkillDiscoveryError",
    "SkillRegistry",
    "SqliteConversationStore",
    "StopReason",
    "TextChunk",
    "TextDelta",
    "ThinkingChunk",
    "Thread",
    "ThreadSpec",
    "ToolCall",
    "ToolCallBegin",
    "ToolOutput",
    "ToolResult",
    "TurnBegin",
    "TurnEnd",
    "TurnResult",
    "UserChunk",
    "Vllm",
    "build_backend",
    "build_computer_description",
    "build_sandbox_tools",
    "build_skills_system_prompt",
    "decode_event_line",
    "default_conversations_root",
    "default_skill_roots",
    "default_threads_root",
    "encode_event_line",
    "load_skill",
    "load_skills_from_root",
    "make_use_skill_tool",
    "reply_text",
    "to_openai_tools",
    "tool",
    "validate_thread_id",
]
