"""Skill 机制 —— 目录形式的操作手册 + on-demand 加载。"""

from __future__ import annotations

from .activation import (
    ActivationError,
    ActivationRequest,
    SkillActivationItem,
    SkillActivationResult,
    SkillActivationService,
    SkillInput,
    SkillMounter,
    make_activate_skill_tool,
    make_activation_use_skill_tool,
    substitute_body,
)
from .builtin import (
    builtin_roots,
)
from .candidate import (
    QualifiedSkillID,
    SkillCandidate,
    SkillDescriptor,
    build_candidate,
    build_descriptor,
    candidates_from_catalog,
    make_skill_id,
    registry_from_candidates,
    validate_agents_frontmatter,
    validate_agents_skill_dir,
)
from .candidate import (
    SkillSource as CandidateSkillSource,
)
from .catalog import (
    CatalogBudgetEntry,
    CatalogBudgetResult,
    MultiCandidateCatalog,
    ResolvedSkill,
    SkillResolutionAmbiguous,
    SkillResolutionError,
    SkillResolver,
    apply_overrides,
    build_catalog,
    build_model_catalog,
    load_catalog_snapshot,
    save_catalog_snapshot,
)
from .catalog_service import (
    SkillCatalogService,
    get_shared_catalog_service,
    reset_shared_catalog_service,
    set_shared_catalog_service,
)
from .discovery import (
    DiscoveredSkill,
    SkillCatalogSnapshot,
    SkillDiagnostic,
    SkillMount,
    SkillSource,
    discover_skill_sources,
    load_skill_catalog,
)
from .installer import (
    InstallError,
    InstallRecord,
    InstallResult,
    SkillInstaller,
    validate_skill_dir,
)
from .mounting import LazySkillMounter, SshLazySkillMounter
from .runtime import SkillRuntime
from .scopes import (
    discover_candidate_sources,
    fingerprint_source,
    load_candidates,
    model_visible_candidates,
    source_rank,
)
from .skill import (
    PROJECT_LOCAL_SKILLS_DIR,
    USER_SKILLS_DIR,
    Skill,
    SkillDiscoveryError,
    SkillRegistry,
    build_skills_system_prompt,
    collect_resources,
    default_skill_roots,
    has_symlinks,
    load_skill,
    load_skills_from_root,
    make_use_skill_tool,
    parse_skill_md,
    validate_skill_name,
)
from .snapshot import (
    SkillResource,
    SkillSetSnapshot,
    SkillSnapshot,
    build_skill_set_snapshot,
    build_skill_snapshot,
    digest_prefix,
)
from .snapstore import (
    PrivateSnapshotStore,
    SkillSnapshotRef,
)
from .state import (
    ExecutionContextState,
    SkillRunView,
    SkillState,
    build_execution_context_state,
)
from .watcher import (
    ContextRoots,
    SkillWatcher,
    discover_with_context_roots,
)

__all__ = [
    "PROJECT_LOCAL_SKILLS_DIR",
    "USER_SKILLS_DIR",
    "ActivationError",
    "ActivationRequest",
    "CandidateSkillSource",
    "ContextRoots",
    "CatalogBudgetEntry",
    "CatalogBudgetResult",
    "DiscoveredSkill",
    "ExecutionContextState",
    "InstallError",
    "InstallRecord",
    "InstallResult",
    "SkillInstaller",
    "validate_skill_dir",
    "LazySkillMounter",
    "MultiCandidateCatalog",
    "PrivateSnapshotStore",
    "QualifiedSkillID",
    "ResolvedSkill",
    "Skill",
    "SkillActivationItem",
    "SkillActivationResult",
    "SkillActivationService",
    "SkillCandidate",
    "SkillCatalogService",
    "SkillCatalogSnapshot",
    "SkillDescriptor",
    "SkillDiagnostic",
    "SkillDiscoveryError",
    "SkillInput",
    "SkillMounter",
    "SkillMount",
    "SkillRegistry",
    "SkillResolutionAmbiguous",
    "SkillResolutionError",
    "SkillResolver",
    "SkillResource",
    "SkillRuntime",
    "SkillRunView",
    "SkillSetSnapshot",
    "SkillSnapshot",
    "SkillSnapshotRef",
    "SkillSource",
    "SkillState",
    "SkillWatcher",
    "SshLazySkillMounter",
    "apply_overrides",
    "build_candidate",
    "builtin_roots",
    "build_catalog",
    "build_descriptor",
    "build_execution_context_state",
    "build_model_catalog",
    "build_skill_set_snapshot",
    "build_skill_snapshot",
    "build_skills_system_prompt",
    "candidates_from_catalog",
    "collect_resources",
    "default_skill_roots",
    "digest_prefix",
    "discover_candidate_sources",
    "discover_with_context_roots",
    "discover_skill_sources",
    "fingerprint_source",
    "get_shared_catalog_service",
    "has_symlinks",
    "load_candidates",
    "make_activate_skill_tool",
    "make_activation_use_skill_tool",
    "load_catalog_snapshot",
    "load_skill",
    "load_skill_catalog",
    "load_skills_from_root",
    "make_skill_id",
    "make_use_skill_tool",
    "model_visible_candidates",
    "parse_skill_md",
    "registry_from_candidates",
    "reset_shared_catalog_service",
    "save_catalog_snapshot",
    "set_shared_catalog_service",
    "source_rank",
    "substitute_body",
    "validate_agents_frontmatter",
    "validate_agents_skill_dir",
    "validate_skill_name",
]
